trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  ConnectedServiceName: '49cdb8b4-9c0c-42ac-aa71-6c404791467a'
  WebAppKind: 'webAppLinux'
  WebAppName: 'SistemaPuntoVenta'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/target'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    preserveTimestamp: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service'
  inputs:
    azureSubscription: '$(ConnectedServiceName)'
    appType: '$(WebAppKind)'
    WebAppName: '$(WebAppName)'
    deployToSlotOrASE: true
    ResourceGroupName: 'WebAPP'
    packageForLinux: '$(System.DefaultWorkingDirectory)/_DonobanR.ProyectoMetodoligas_Copia (16)/drop'
    RuntimeStack: 'TOMCAT|10.1-java17'
